export enum Department {
  ADMIN = "行政會議",
  CROSS_DEPT = "跨科會議",
  GRAND_ROUND = "Grand round",
  CHILD = "兒童牙科",
  RESTORATIVE = "牙體復形科",
  ENDODONTIC = "牙髓病科",
  PERIODONTIC = "牙周病科",
  ORAL_SURGERY = "口腔外科",
  FAMILY = "家庭牙醫科",
  PATHOLOGY = "口腔病理科",
  PROSTHODONTIC = "義齒補綴科",
  ORTHODONTIC = "齒列矯正科",
  GENERAL = "一般牙科",
  OTHER = "其他會議"
}

export const DEPARTMENT_CONTENTS: Record<string, string[]> = {
  [Department.ADMIN]: ["口醫部科會", "教學行政會議", "親善之家會議", "其他"],
  [Department.CROSS_DEPT]: ["跨科病例討論會", "頭頸癌團隊tumor board會議", "病歷寫作", "廠商課程", "其他"],
  [Department.GRAND_ROUND]: ["全人醫療", "病人安全", "醫療品質", "醫病溝通", "醫學倫理", "醫事法規", "感染管制", "實證醫學", "病歷寫作", "新知專題", "其他"],
  [Department.CHILD]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.RESTORATIVE]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.ENDODONTIC]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.PERIODONTIC]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.ORAL_SURGERY]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.FAMILY]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.PATHOLOGY]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.PROSTHODONTIC]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.ORTHODONTIC]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.GENERAL]: ["核心課程", "journal reading", "book reading", "case report", "video case", "其他"],
  [Department.OTHER]: []
};

export enum Frequency {
  ONCE_A_MONTH = "每個月一次",
  TWICE_A_MONTH = "每個月兩次",
  ONCE_EVERY_TWO_MONTHS = "每兩個月一次",
  ONCE_A_QUARTER = "每季一次",
  WEEKLY = "每週一次",
  MONTHLY_NTH_DAY = "每月固定時間",
  EVERY_YEAR = "每年一次",
  SPECIFIC = "直接輸入時間"
}

export interface Meeting {
  id: string;
  department: Department;
  content: string;
  date: Date;
  startTime: string; // HH:mm
  endTime: string;   // HH:mm
  isAutoGenerated: boolean;
  groupId?: string; // For bulk operations if needed
  
  // New fields
  topic?: string;
  location?: string;
  advisors?: string[];
  presenter?: string;
  recorder?: string;
  remarks?: string;
}

export interface AppSettings {
  advisors: string[];
  locations: string[];
  participants: string[];
}
